/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIPlayerApi.h"

#include "com.l3vels.client.model/OpenAPICreatePlayerInput.h"
#include "com.l3vels.client.model/OpenAPIPlayer.h"
#include "com.l3vels.client.model/OpenAPIPlayerAsset.h"

namespace OpenAPI
{

/* Count players
 *
 * Count players in game. Example: count players in game Call of Duty.
*/
class OPENAPI_API OpenAPIPlayerApi::CountPlayersByGameIdRequest : public Request
{
public:
    virtual ~CountPlayersByGameIdRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* API key is associated with multiple games. Please include it in to use developers API. */
	FString Authorization;
	/* Game Id */
	FString GameId;
};

class OPENAPI_API OpenAPIPlayerApi::CountPlayersByGameIdResponse : public Response
{
public:
    virtual ~CountPlayersByGameIdResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    double Content;
};

/* Create new player
 *
 * Create new player for Game. Example: Create new player Jack in game Call of Duty.
*/
class OPENAPI_API OpenAPIPlayerApi::CreatePlayerRequest : public Request
{
public:
    virtual ~CreatePlayerRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* API key is associated with multiple games. Please include it in to use developers API. */
	FString Authorization;
	OpenAPICreatePlayerInput OpenAPICreatePlayerInput;
};

class OPENAPI_API OpenAPIPlayerApi::CreatePlayerResponse : public Response
{
public:
    virtual ~CreatePlayerResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIPlayer Content;
};

/* Retrieve player asset by ID
 *
 * Retrieve player asset by ID. Player asset represents a single asset that a player owns. It has amount field that represents how many of this asset player owns.
*/
class OPENAPI_API OpenAPIPlayerApi::GetPlayerAssetByIdRequest : public Request
{
public:
    virtual ~GetPlayerAssetByIdRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* API key is associated with multiple games. Please include it in to use developers API. */
	FString Authorization;
	FString Id;
	FString GameId;
};

class OPENAPI_API OpenAPIPlayerApi::GetPlayerAssetByIdResponse : public Response
{
public:
    virtual ~GetPlayerAssetByIdResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIPlayerAsset Content;
};

/* Retrieve player by ID
 *
 * Retrieves a specific player by ID associated with Game. Example: retrieve player Jack from game Call of Duty.
*/
class OPENAPI_API OpenAPIPlayerApi::GetPlayerByIdRequest : public Request
{
public:
    virtual ~GetPlayerByIdRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* API key is associated with multiple games. Please include it in to use developers API. */
	FString Authorization;
	/* Player ID that you created in your Game. Example: Jack, George, etc. */
	FString Id;
	/* Game ID to find asset in. Example: Call of Duty, Fortnite, etc. */
	FString GameId;
};

class OPENAPI_API OpenAPIPlayerApi::GetPlayerByIdResponse : public Response
{
public:
    virtual ~GetPlayerByIdResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIPlayer Content;
};

/* Retrieve players
 *
 * Retrieve a list of players that match the specified filter criteria. Developers can use this method to retrieve players by name, category, status, or other properties. Example: Retrieve players from game Call of Duty.
*/
class OPENAPI_API OpenAPIPlayerApi::GetPlayersRequest : public Request
{
public:
    virtual ~GetPlayersRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* API key is associated with multiple games. Please include it in to use developers API. */
	FString Authorization;
	/* Game ID to find player in your game. Example: Fortnite, Minecraft, etc. */
	FString GameId;
	/* Player field to sort by. You can sort by name, created_on and etc. */
	TOptional<FString> Sort;
	/* Sort order (ASC for ascending or DESC for descending) */
	TOptional<FString> Order;
	/* Search player by name */
	TOptional<FString> SearchText;
	/* Number of players to return per page */
	TOptional<double> Limit;
	/* Page number */
	TOptional<double> Page;
};

class OPENAPI_API OpenAPIPlayerApi::GetPlayersResponse : public Response
{
public:
    virtual ~GetPlayersResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    TArray<OpenAPIPlayer> Content;
};

/* Retrieve player assets
 *
 * This API method retrieves a list of Player assets that match the specified filter criteria. Developers can use this method to retrieve Player assets by player, Game or other properties.
*/
class OPENAPI_API OpenAPIPlayerApi::PlayerAssetsRequest : public Request
{
public:
    virtual ~PlayerAssetsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* API key is associated with multiple games. Please include it in to use developers API. */
	FString Authorization;
	/* Game ID to find player assets in your game. Example: Fortnite, Minecraft, etc. */
	FString GameId;
	/* Game ID to find player assets in your game. Example: Fortnite, Minecraft, etc. */
	TOptional<FString> AssetId;
	/* Game ID to find player assets in your game. Example: Fortnite, Minecraft, etc. */
	TOptional<FString> PlayerId;
	/* Player asset field to sort by. You can sort by name, created_on and etc. */
	TOptional<FString> Sort;
	/* Sort order (ASC for ascending or DESC for descending) */
	TOptional<FString> Order;
	/* Number of player assets to return per page */
	TOptional<double> Limit;
	/* Page number */
	TOptional<double> Page;
};

class OPENAPI_API OpenAPIPlayerApi::PlayerAssetsResponse : public Response
{
public:
    virtual ~PlayerAssetsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    TArray<OpenAPIPlayerAsset> Content;
};

/* Update an existing Player
 *
 * This API method allows developers to update an existing Player by providing the ID of the Player and the updated properties and associated assets.
*/
class OPENAPI_API OpenAPIPlayerApi::UpdatePlayerRequest : public Request
{
public:
    virtual ~UpdatePlayerRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* API key is associated with multiple games. Please include it in to use developers API. */
	FString Authorization;
};

class OPENAPI_API OpenAPIPlayerApi::UpdatePlayerResponse : public Response
{
public:
    virtual ~UpdatePlayerResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIPlayer Content;
};

}
