/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIUtilitiesApi.h"


namespace OpenAPI
{

/* 

*/
class OPENAPI_API OpenAPIUtilitiesApi::UtilityControllerHealthRequest : public Request
{
public:
    virtual ~UtilityControllerHealthRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

};

class OPENAPI_API OpenAPIUtilitiesApi::UtilityControllerHealthResponse : public Response
{
public:
    virtual ~UtilityControllerHealthResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    
};

}
