/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

class OPENAPI_API OpenAPIGameApi
{
public:
	OpenAPIGameApi();
	~OpenAPIGameApi();

	/* Sets the URL Endpoint.
	* Note: several fallback endpoints can be configured in request retry policies, see Request::SetShouldRetry */
	void SetURL(const FString& Url);

	/* Adds global header params to all requests */
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	/* Sets the retry manager to the user-defined retry manager. User must manage the lifetime of the retry manager.
	* If no retry manager is specified and a request needs retries, a default retry manager will be used.
	* See also: Request::SetShouldRetry */
	void SetHttpRetryManager(FHttpRetrySystem::FManager& RetryManager);
	FHttpRetrySystem::FManager& GetHttpRetryManager();

	class CreateGameRequest;
	class CreateGameResponse;
	class GameControllerGetGamesRequest;
	class GameControllerGetGamesResponse;
	class GetGameByIdRequest;
	class GetGameByIdResponse;
	
    DECLARE_DELEGATE_OneParam(FCreateGameDelegate, const CreateGameResponse&);
    DECLARE_DELEGATE_OneParam(FGameControllerGetGamesDelegate, const GameControllerGetGamesResponse&);
    DECLARE_DELEGATE_OneParam(FGetGameByIdDelegate, const GetGameByIdResponse&);
    
    FHttpRequestPtr CreateGame(const CreateGameRequest& Request, const FCreateGameDelegate& Delegate = FCreateGameDelegate()) const;
    FHttpRequestPtr GameControllerGetGames(const GameControllerGetGamesRequest& Request, const FGameControllerGetGamesDelegate& Delegate = FGameControllerGetGamesDelegate()) const;
    FHttpRequestPtr GetGameById(const GetGameByIdRequest& Request, const FGetGameByIdDelegate& Delegate = FGetGameByIdDelegate()) const;
    
private:
    void OnCreateGameResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FCreateGameDelegate Delegate) const;
    void OnGameControllerGetGamesResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGameControllerGetGamesDelegate Delegate) const;
    void OnGetGameByIdResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetGameByIdDelegate Delegate) const;
    
	FHttpRequestRef CreateHttpRequest(const Request& Request) const;
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
	mutable FHttpRetrySystem::FManager* RetryManager = nullptr;
	mutable TUniquePtr<HttpRetryManager> DefaultRetryManager;
};

}
