/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

class OPENAPI_API OpenAPITransactionApi
{
public:
	OpenAPITransactionApi();
	~OpenAPITransactionApi();

	/* Sets the URL Endpoint.
	* Note: several fallback endpoints can be configured in request retry policies, see Request::SetShouldRetry */
	void SetURL(const FString& Url);

	/* Adds global header params to all requests */
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	/* Sets the retry manager to the user-defined retry manager. User must manage the lifetime of the retry manager.
	* If no retry manager is specified and a request needs retries, a default retry manager will be used.
	* See also: Request::SetShouldRetry */
	void SetHttpRetryManager(FHttpRetrySystem::FManager& RetryManager);
	FHttpRetrySystem::FManager& GetHttpRetryManager();

	class GetTransactionByIdRequest;
	class GetTransactionByIdResponse;
	class GetTransactionsRequest;
	class GetTransactionsResponse;
	class TransactionControllerWebhookRequest;
	class TransactionControllerWebhookResponse;
	
    DECLARE_DELEGATE_OneParam(FGetTransactionByIdDelegate, const GetTransactionByIdResponse&);
    DECLARE_DELEGATE_OneParam(FGetTransactionsDelegate, const GetTransactionsResponse&);
    DECLARE_DELEGATE_OneParam(FTransactionControllerWebhookDelegate, const TransactionControllerWebhookResponse&);
    
    FHttpRequestPtr GetTransactionById(const GetTransactionByIdRequest& Request, const FGetTransactionByIdDelegate& Delegate = FGetTransactionByIdDelegate()) const;
    FHttpRequestPtr GetTransactions(const GetTransactionsRequest& Request, const FGetTransactionsDelegate& Delegate = FGetTransactionsDelegate()) const;
    FHttpRequestPtr TransactionControllerWebhook(const TransactionControllerWebhookRequest& Request, const FTransactionControllerWebhookDelegate& Delegate = FTransactionControllerWebhookDelegate()) const;
    
private:
    void OnGetTransactionByIdResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetTransactionByIdDelegate Delegate) const;
    void OnGetTransactionsResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetTransactionsDelegate Delegate) const;
    void OnTransactionControllerWebhookResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FTransactionControllerWebhookDelegate Delegate) const;
    
	FHttpRequestRef CreateHttpRequest(const Request& Request) const;
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
	mutable FHttpRetrySystem::FManager* RetryManager = nullptr;
	mutable TUniquePtr<HttpRetryManager> DefaultRetryManager;
};

}
