/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPISetSaleStatusDto
 *
 * 
 */
class OPENAPI_API OpenAPISetSaleStatusDto : public Model
{
public:
    virtual ~OpenAPISetSaleStatusDto() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Project Id */
	FString ProjectId;
	/* Collection Id */
	FString CollectionId;
	/* Sale Status of the contract */
	TSharedPtr<FJsonObject> SaleStatus;
};

}
