/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPICreatePlayerInput
 *
 * 
 */
class OPENAPI_API OpenAPICreatePlayerInput : public Model
{
public:
    virtual ~OpenAPICreatePlayerInput() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* You can send your generated unique ID for player if it's handy for game. If field is empty, we will generate unique ID. */
	TOptional<FString> UniqueId;
	/* The name of the player. */
	FString Name;
	/* The username of the player. */
	TOptional<FString> Username;
	/* The email of the player. */
	TOptional<FString> Email;
	/* The image URL of the player avatar. */
	TOptional<FString> Avatar;
	/* Game ID to create the player for. Example: Create player Jack for game Fortnite. */
	FString GameId;
	/* Should create wallet for player or not. */
	TOptional<bool> IsCreateWallet;
	/* Custom props for player. */
	TOptional<TArray<FString>> CustomProps;
};

}
