/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "com.l3vels.client.model/OpenAPIAsset.h"

namespace OpenAPI
{

/*
 * OpenAPIAssetsResponse
 *
 * 
 */
class OPENAPI_API OpenAPIAssetsResponse : public Model
{
public:
    virtual ~OpenAPIAssetsResponse() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Number of assets to return per page */
	TArray<OpenAPIAsset> Items;
	/* Number of total items */
	double Total;
	/* Number of items to return per page */
	double Limit;
	/* Page number */
	double Page;
};

}
