/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPIMintBatchDto
 *
 * 
 */
class OPENAPI_API OpenAPIMintBatchDto : public Model
{
public:
    virtual ~OpenAPIMintBatchDto() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Project Id */
	FString ProjectId;
	/* Collection Id */
	FString CollectionId;
	/* Player address to mint token to */
	FString PlayerAddress;
	/* Player ID to mint to. You can provide this or player_address */
	FString PlayerId;
	/* Array of tokens to mint */
	TArray<FString> Assets;
};

}
