/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPIUpdateAssetDto
 *
 * 
 */
class OPENAPI_API OpenAPIUpdateAssetDto : public Model
{
public:
    virtual ~OpenAPIUpdateAssetDto() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The name of the asset. */
	TOptional<FString> Name;
	/* The story of asset. */
	TOptional<FString> Description;
	/* Price of asset */
	TOptional<double> Price;
	/* Supply of asset */
	TOptional<double> Supply;
	/* Asset URL */
	TOptional<FString> AssetUrl;
	/* Custom props for asset. */
	TOptional<TSharedPtr<FJsonObject>> CustomProps;
	/* Collection ID to find and update the asset in. Example: Update AK-47 asset in Weapons collection. */
	FString CollectionId;
	/* Game/project ID to update the asset in. Example: Call of Duty */
	FString ProjectId;
};

}
