/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPITokenDto
 *
 * 
 */
class OPENAPI_API OpenAPITokenDto : public Model
{
public:
    virtual ~OpenAPITokenDto() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Token ID to mint. You can provide this or asset_id */
	TOptional<double> TokenId;
	/* Asset ID to mint. You can provide this or token_id */
	TOptional<FString> AssetId;
	/* Amount to mint */
	double Amount;
};

}
