/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPIPlayerAsset
 *
 * 
 */
class OPENAPI_API OpenAPIPlayerAsset : public Model
{
public:
    virtual ~OpenAPIPlayerAsset() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The unique identifier for the Player asset entity. */
	FString Id;
	/* The amount of the specific asset that the player has. */
	double Amount;
	/* The unique identifier of the player that the asset is associated with. */
	FString PlayerId;
	/* The unique identifier of the asset that the asset is associated with. */
	FString AssetId;
	/* The unique identifier of the collection that the Player asset is associated with. */
	FString CollectionId;
	/* The unique identifier of the account that the Player belongs to. */
	FString AccountId;
	/* The unique identifier of the game that the Player is associated with. This allows developers to organize their players by game and helps with tracking and reporting. */
	FString GameId;
	/* The date when the player was created. */
	FDateTime CreatedOn;
	/* The date when the player was last modified. */
	FDateTime ModifiedOn;
	/* The Id of the user who created the player. */
	FString CreatedBy;
	/* The Id of the user who last modified the player. */
	FString ModifiedBy;
};

}
