/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIModule.h"

IMPLEMENT_MODULE(OpenAPIModule, OpenAPI);
DEFINE_LOG_CATEGORY(LogOpenAPI);

void OpenAPIModule::StartupModule()
{
}

void OpenAPIModule::ShutdownModule()
{
}
