/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIAssetsResponseDto.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIAssetsResponseDto::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("items")); WriteJsonValue(Writer, Items);
	Writer->WriteIdentifierPrefix(TEXT("total")); WriteJsonValue(Writer, Total);
	Writer->WriteIdentifierPrefix(TEXT("limit")); WriteJsonValue(Writer, Limit);
	Writer->WriteIdentifierPrefix(TEXT("page")); WriteJsonValue(Writer, Page);
	Writer->WriteObjectEnd();
}

bool OpenAPIAssetsResponseDto::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("items"), Items);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("total"), Total);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("limit"), Limit);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("page"), Page);

	return ParseSuccess;
}

}
