/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIUpdateAssetInput.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIUpdateAssetInput::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Name.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name.GetValue());
	}
	if (Description.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("description")); WriteJsonValue(Writer, Description.GetValue());
	}
	if (Price.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("price")); WriteJsonValue(Writer, Price.GetValue());
	}
	if (Supply.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("supply")); WriteJsonValue(Writer, Supply.GetValue());
	}
	if (AssetUrl.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("asset_url")); WriteJsonValue(Writer, AssetUrl.GetValue());
	}
	if (CustomProps.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("custom_props")); WriteJsonValue(Writer, CustomProps.GetValue());
	}
	Writer->WriteIdentifierPrefix(TEXT("collection_id")); WriteJsonValue(Writer, CollectionId);
	Writer->WriteIdentifierPrefix(TEXT("game_id")); WriteJsonValue(Writer, GameId);
	Writer->WriteObjectEnd();
}

bool OpenAPIUpdateAssetInput::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("name"), Name);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("description"), Description);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("price"), Price);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("supply"), Supply);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("asset_url"), AssetUrl);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("custom_props"), CustomProps);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("collection_id"), CollectionId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("game_id"), GameId);

	return ParseSuccess;
}

}
