/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIPlayer.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIPlayer::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("id")); WriteJsonValue(Writer, Id);
	Writer->WriteIdentifierPrefix(TEXT("unique_id")); WriteJsonValue(Writer, UniqueId);
	Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name);
	Writer->WriteIdentifierPrefix(TEXT("username")); WriteJsonValue(Writer, Username);
	Writer->WriteIdentifierPrefix(TEXT("email")); WriteJsonValue(Writer, Email);
	Writer->WriteIdentifierPrefix(TEXT("avatar")); WriteJsonValue(Writer, Avatar);
	Writer->WriteIdentifierPrefix(TEXT("custom_props")); WriteJsonValue(Writer, CustomProps);
	Writer->WriteIdentifierPrefix(TEXT("last_seen")); WriteJsonValue(Writer, LastSeen);
	Writer->WriteIdentifierPrefix(TEXT("account_id")); WriteJsonValue(Writer, AccountId);
	Writer->WriteIdentifierPrefix(TEXT("project_id")); WriteJsonValue(Writer, ProjectId);
	Writer->WriteIdentifierPrefix(TEXT("created_on")); WriteJsonValue(Writer, CreatedOn);
	Writer->WriteIdentifierPrefix(TEXT("modified_on")); WriteJsonValue(Writer, ModifiedOn);
	Writer->WriteIdentifierPrefix(TEXT("created_by")); WriteJsonValue(Writer, CreatedBy);
	Writer->WriteIdentifierPrefix(TEXT("modified_by")); WriteJsonValue(Writer, ModifiedBy);
	Writer->WriteIdentifierPrefix(TEXT("is_create_wallet")); WriteJsonValue(Writer, IsCreateWallet);
	Writer->WriteObjectEnd();
}

bool OpenAPIPlayer::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("id"), Id);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("unique_id"), UniqueId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("name"), Name);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("username"), Username);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("email"), Email);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("avatar"), Avatar);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("custom_props"), CustomProps);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("last_seen"), LastSeen);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("account_id"), AccountId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("project_id"), ProjectId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("created_on"), CreatedOn);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("modified_on"), ModifiedOn);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("created_by"), CreatedBy);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("modified_by"), ModifiedBy);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("is_create_wallet"), IsCreateWallet);

	return ParseSuccess;
}

}
