/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * OpenAPI spec version: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIMintInput.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIMintInput::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("game_id")); WriteJsonValue(Writer, GameId);
	Writer->WriteIdentifierPrefix(TEXT("collection_id")); WriteJsonValue(Writer, CollectionId);
	if (PlayerAddress.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("player_address")); WriteJsonValue(Writer, PlayerAddress.GetValue());
	}
	if (PlayerId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("player_id")); WriteJsonValue(Writer, PlayerId.GetValue());
	}
	Writer->WriteIdentifierPrefix(TEXT("asset")); WriteJsonValue(Writer, Asset);
	Writer->WriteObjectEnd();
}

bool OpenAPIMintInput::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("game_id"), GameId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("collection_id"), CollectionId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("player_address"), PlayerAddress);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("player_id"), PlayerId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("asset"), Asset);

	return ParseSuccess;
}

}
