name: Generate and Push

on:
  repository_dispatch:
    types: [generate_and_push]

jobs:
  generate_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set environment variables
      env:
        OPEN_API_URL: ${{ github.event.client_payload.open_api_url }}
        PACKAGE_VERSION: ${{ github.event.client_payload.package_version }}
        COMMIT_NAME: ${{ github.event.client_payload.commit_name }}
        USERNAME: ${{ secrets.GITHUB_USERNAME }}
        USER_EMAIL: ${{ secrets.GITHUB_USER_EMAIL }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        # Call the generate_and_push.sh script and pass the environment variables
        ./generate_and_push.sh "$OPEN_API_URL" "$PACKAGE_VERSION" "$COMMIT_NAME"
